## Make School-level Forbes 400 Alumni By Sector Counts

### For Table 4 of Elite Embeddedness

By Charlie Eaton and Albina Gibadullina

In [2]:
use d_forbes400_alum_board_1989_2003_2017, clear

In [3]:
set more off

use id boardunitid1 boardunitid2 mbaunitid collegeunitid  ///
boardtop30private boardtop30public pehedge otherfin technology worth inherited ///
collegeschooltype mbaschooltype year using d_forbes400_alum_board_1989_2003_2017, clear
keep if year==2003 | year==2017
drop if boardunitid1==.

collapse (count) forbesboard1=id (sum) otherboard1=other inheritedboard1=inherited pehedgeboard1=pehedge otherfinboard1=otherfin ///
technologyboard1=technology, by (boardunitid1 year)
sum pehedge otherfin technology forbesboard
rename boardunitid1 unitid
save d_board1_forbes_400_count, replace

use id boardunitid1 boardunitid2 mbaunitid collegeunitid  ///
boardtop30private boardtop30public pehedge otherfin technology worth inherited ///
collegeschooltype mbaschooltype year using d_forbes400_alum_board_1989_2003_2017, clear
keep if year==2003 | year==2017
drop if boardunitid2==.

collapse (count) forbesboard2=id (sum) otherboard2=other inheritedboard2=inherited pehedgeboard2=pehedge otherfinboard2=otherfin ///
technologyboard2=technology, by (boardunitid2 year)
sum pehedge otherfin tech forbesboard
rename boardunitid2 unitid
save d_board2_forbes_400_count, replace

use id boardunitid1 boardunitid2 mbaunitid collegeunitid  ///
boardtop30private boardtop30public pehedge otherfin technology worth inherited ///
collegeschooltype mbaschooltype year using d_forbes400_alum_board_1989_2003_2017, clear
keep if year==2003 | year==2017
drop if mbaunitid==.

gen other=0
replace other=1 if pehedge!=1 & otherfin!=1 & technology!=1
*foreach var in pehedge otherfin technology other {
*    replace `var'=0 if inherited==1
*}

collapse (count)forbes_mba=id (sum) other_mba=other inherited_mba=inherited pehedge_mba=pehedge otherfin_mba=otherfin ///
technology_mba=technology, by (mbaunitid year)
sum pehedge otherfin tech forbes
rename mbaunitid unitid
save d_mba_forbes_400_count, replace

use id boardunitid1 boardunitid2 mbaunitid collegeunitid  ///
boardtop30private boardtop30public pehedge otherfin technology worth inherited ///
collegeschooltype mbaschooltype year using d_forbes400_alum_board_1989_2003_2017, clear
keep if year==2003 | year==2017
drop if collegeunitid==.

gen other=0
replace other=1 if pehedge!=1 & otherfin!=1 & technology!=1
*foreach var in pehedge otherfin technology other {
*    replace `var'=0 if inherited==1
*}

collapse (count)forbes_ba=id (sum) other_ba=other inherited_ba=inherited pehedge_ba=pehedge otherfin_ba=otherfin ///
technology_ba=technology, by (collegeunitid year)
sum pehedge otherfin tech forbes
rename collegeunitid unitid
save d_ba_forbes_400_count, replace

use id boardunitid1 boardunitid2 mbaunitid collegeunitid jdunitid  ///
boardtop30private boardtop30public pehedge otherfin technology worth inherited ///
collegeschooltype mbaschooltype year using d_forbes400_alum_board_1989_2003_2017, clear
keep if year==2003 | year==2017
drop if jdunitid==.

gen other=0
replace other=1 if pehedge!=1 & otherfin!=1 & technology!=1
*foreach var in pehedge otherfin technology other {
*    replace `var'=0 if inherited==1
*}

collapse (count)forbes_jd=id (sum) other_jd=other inherited_jd=inherited pehedge_jd=pehedge otherfin_jd=otherfin ///
technology_jd=technology, by (jdunitid year)
sum pehedge otherfin tech forbes
rename jdunitid unitid
save d_jd_forbes_400_count, replace

(400 observations deleted)
(666 observations deleted)

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
pehedgeboa~1 |         60         .55    .7231054          0          3
otherfinbo~1 |         60         .25    .5407152          0          2
technology~1 |         60    .2166667    .4544196          0          2
forbesboard1 |         60    2.233333    1.880918          1          8
file d_board1_forbes_400_count.dta saved
(400 observations deleted)
(794 observations deleted)

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
pehedgeboa~2 |          5          .4    .5477226          0          1
otherfinbo~2 |          5           0           0          0          0
technology~2 |          5           0           0          0          0
forbesboard2 |          5         1.2    .4472136          1          2
file d_board2_forbes_400_count.dta saved
(400 observations deleted)
(671 observations deleted)
(52 real changes made)

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
 pehedge_mba |         32     1.34375    2.322532          0         11
otherfin_mba |         32      .71875    1.054464          0          4
technology~a |         32      .34375    .7006621          0          3
  forbes_mba |         32     4.03125    5.474188          1         24
file d_mba_forbes_400_count.dta saved
(400 observations deleted)
(259 observations deleted)
(317 real changes made)

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
  pehedge_ba |        198    .4848485    1.097886          0          8
 otherfin_ba |        198    .3080808    .5884121          0          3
technology~a |        198    .3383838    .8559386          0          6
   forbes_ba |        198    2.732323    3.172545          1         19
file d_ba_forbes_400_count.dta saved
(400 observations deleted)
(756 observations deleted)
(23 real changes made)

    Variable |        Obs        Mean    Std. dev.       Min        Max
-------------+---------------------------------------------------------
  pehedge_jd |         24          .5    .6593805          0          2
 otherfin_jd |         24    .3333333    .4815434          0          1
technology~d |         24    .0416667    .2041241          0          1
   forbes_jd |         24    1.833333     1.00722          1          4
file d_jd_forbes_400_count.dta saved